version: '3'

services:
  stan:
    build: ./stan
    command: python app.py
    volumes:
      - ./stan:/app
    ports:
      - '5000:80'
    networks:
      - southpark-elementary

  kyle:
    build: ./kyle
    command: python app.py
    volumes:
      - ./kyle:/app
    ports:
      - '5000:80'
    networks:
      - southpark-elementary

  kenny:
    build: ./kenny
    command: nodemon server.js
    volumes:
      - ./kenny:/app
    ports:
      - '5001:80'
      - '5858:5858'

  eric:
    build:
      context: ./eric
    depends_on:
      - stan
      - kenny
    networks:
      - southpark-elementary

  butters:
    image: butters:alpine
    container_name: butters
    ports: ['6379']
    networks:
      - southpark-elementary

  chef:
    image: postgres:9.4
    container_name: chef
    environment:
      POSTGRES: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  randy:
    build: ./randy
    command: python app.py
    volumes:
      - ./randy:/app
    ports:
      - '5000:80'

  bebe:
    build: ./bebe
    command: python app.py
    volumes:
      - ./bebe:/app
    ports:
      - '5000:80'

  token:
    build: ./token
    command: nodemon server.js
    volumes:
      - ./token:/app
    ports:
      - '5001:80'
      - '5858:5858'

  michaeljackson:
    build: ./michaeljackson
    command: nodemon server.js
    volumes:
      - ./michaeljackson:/app
    ports:
      - '5001:80'
      - '5858:5858'
    networks:
      - mr.slave
      - big-gay-al's

  towelie:
    build:
      context: ./towelie
    depends_on:
      - randy
      - kenny
    networks:
      - big-gay-al's

  sheila:
    build:
      context: ./sheila
    depends_on:
      - sharon
    networks:
      - southpark-elementary

  timmy:
    build:
      context: ./timmy
    depends_on:
      - sharon
    networks:
      - southpark-elementary

  sharon:
    build:
      context: ./sharon
    depends_on:
      - randy

  mr.garrison:
    image: mr.garrison:alpine
    container_name: mr.garrison
    ports: ['6379']
    networks:
      - mr.slave

  slave:
    image: slave:alpine
    container_name: slave
    ports: ['6379']
    networks:
      - mr.slave

  tweak:
    image: postgres:9.4
    container_name: tweak
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'tweak-data:/var/lib/postgresql/data'
    networks:
      - southpark-elementary

  lean:
    image: postgres:9.4
    container_name: lean
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'tweak-data:/var/lib/postgresql/data'
    networks:
      - mr.slave

volumes:
  chef-data:
  tweak-data:

networks:
  southpark-elementary:
  big-gay-al's:
  mr.slave:
  imaginaaaaation:
