version: '3.2'
services:
  web:
    build: web
    command: python app.py
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./web:/code # modified here to take into account the new app path
    links:
      - redis
    environment:
      - DATADOG_HOST=datadog # used by the web app to initialize the Datadog library
  redis:
    image: redis
  # agent section
  datadog:
    build: datadog
    links:
      - redis # ensures that redis is a host that the container can find
      - web # ensures that the web app can send metrics
    environment:
      - DD_API_KEY=__your_datadog_api_key_here__
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
